version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.txt
    image: sandrinerv/srv-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./data:/data
    networks:
      - project_network

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.txt
    image: sandrinerv/srv-frontend:latest
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
      - ./data:/data
    networks:
      - project_network

networks:
  project_network: