FROM python:3.8.15@sha256:7c5b3ec91b7e4131dead176d824ddf317e6c19fe1ae38c54ec0ae6038908dd18

WORKDIR /app

COPY requirements-frontend.txt requirements-frontend.txt

RUN pip install -r requirements-frontend.txt

COPY . /app

EXPOSE 8501

CMD ["streamlit", "run", "dashboard.py"]