FROM python:3.8.15

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-backend.txt requirements.txt

RUN pip install -r requirements.txt

COPY . /app

EXPOSE 8000

HEALTHCHECK CMD curl --fail http://localhost: 8000/_stcore/health

CMD ["uvicorn", "fast_api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
