FROM python:3.8.15@sha256:7c5b3ec91b7e4131dead176d824ddf317e6c19fe1ae38c54ec0ae6038908dd18

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-backend.txt requirements.txt

RUN pip install -r requirements.txt

COPY . /app

EXPOSE 8000 80

ENV PORT 80

HEALTHCHECK CMD curl --fail http://localhost: 8000/_stcore/health

CMD ["uvicorn", "fast_api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
