name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.13 # This is the action
        with:
          heroku_api_key: ${{secrets.e8d6aa64-ef9b-4eaf-8df5-aea916243555}}
          heroku_app_name: "ocr7-dashboard-app2" #Must be unique in Heroku
          heroku_email: "sandrine.veloso@gmail.com"
          appdir: "streamlit"