# Your workflow name.
name: Deploy to heroku.

# Run workflow on every push to master branch.
on:
  [push]

working_directory: /streamlit

#set environment variables 
env:
  HEROKU_API_KEY: ${{ secrets.e8d6aa64-ef9b-4eaf-8df5-aea916243555 }}
  APP_NAME: ${{ 'ocr7-dashboard-app' }}

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:

    # Clone the repository
    - name: Checkout
      uses: actions/checkout@v2

    # Build Docker image
    - name: Docker build
      run : docker buildx build --load --platform linux/amd64 -t registry.heroku.com/ocr7-fastapi-app/web .
      # run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

    # Push the Docker image to Heroku Container Registry
    - name: Publish
      run: |
        docker push registry.heroku.com/ocr7-fastapi-app/web:latest                
        heroku container:release web -a ocr7-dashboard-app 