# Your workflow name.
name: Deploy to heroku.

# Run workflow on every push to master branch.
on:
  [push]

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps: 

    # Clone the repository
    - name: Checkout
      uses: actions/checkout@v2

    # Build Docker image
    - name: Build image
      run : docker build -t registry.heroku.com/ocr7-dashboard-app/web .
      # run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

    # Push the Docker image to Heroku Container Registry
    - name: Publish
      run: |
        docker push registry.heroku.com/ocr7-dashboard-app/web:latest                
        heroku container:release web -a ocr7-dashboard-app 